"""add name

Revision ID: 383ad3d4c75b
Revises: 51768860f7c2
Create Date: 2021-07-27 19:42:39.255124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383ad3d4c75b'
down_revision = '51768860f7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_store', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_store', 'name')
    # ### end Alembic commands ###
